language: java
jdk:
  - oraclejdk8
addons:
  sonarqube:
    organization: "randomreaper-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn test -B
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

